---
- hosts: 'all'
  tasks:
    - include_role:
        name: '{{ ansible_os_family }}_pkgs'
    - include_role:
        name: 'common'
    - include_role:
        name: '{{ ansible_os_family }}_cfgs'
