---
- name: 'Create directories.'
  file:
    path: '{{ item }}'
    state: 'directory'
  loop: '{{ dirs }}'

- name: 'Place symlinks.'
  file:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    state: 'link'
  loop: '{{ symlinks }}'

- name: 'Enable custom services.'
  command: 'launchctl load -w {{ item }} 2> /dev/null'
  loop:
    - '~/Library/LaunchAgents/gnu.emacs.daemon.plist'

- name: 'Get names of font files installed by common role.'
  command: 'find ~/.fonts \( -name "*.[ot]tf" -or -name "*.pcf.gz" \) -type f'
  register: 'font_files'

- name: 'Install fonts.'
  command: 'cp "{{ item }}" ~/Library/Fonts'
  loop: '{{ font_files.stdout_lines }}'

- name: 'Show system folders.'
  command: 'chflags nohidden {{ item }}'
  become: yes
  loop:
    - '~/Library'
    - '/Volumes'

- name: 'Configure power management settings.'
  command: 'pmset -a {{ item.setting }} {{ item.value }}'
  become: yes
  loop:
    # Set standby delay to 24 hours.
    - setting: 'standbydelay'
      value: '86400'
    # Turn hibernate off.
    - setting: 'hibernatemode'
      value: '0'

- name: 'Set systemsetup parameters.'
  command: 'systemsetup -{{ item.param }} {{ item.value }}'
  become: yes
  loop:
    # Restart automatically if the system freezes.
    - param: 'setrestartfreeze'
      value: 'on'
    # Never go into computer sleep mode.
    - param: 'setcomputersleep'
      value: 'off'

- name: 'Set osx defaults.'
  osx_defaults:
    host: '{{ item.host | default(omit) }}'
    domain: '{{ item.domain | default(omit) }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: '{{ item.state | default("present") }}'
  become: '{{ item.become | default(omit) }}'
  loop: '{{ osx_defaults }}'
  ignore_errors: '{{ item.ignore_errors | default(omit) }}'

- name: 'Delete plist entries.'
  command: '/usr/libexec/PlistBuddy -c "Delete {{ item.key }}" {{ item.plist }}'
  ignore_errors: 'yes'
  loop: '{{ plist_entries }}'

- name: 'Add plist entries.'
  command: '/usr/libexec/PlistBuddy -c "Add {{ item.key }} {{ item.type }} {{ item.value }}" {{ item.plist }}'
  loop: '{{ plist_entries }}'

- name: 'Expand the following File Info panes: "General", "Open with", and "Sharing & Permissions".'
  command: 'defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true'

- name: 'Disable system services.'
  command: 'launchctl unload -w {{ item }} 2> /dev/null'
  loop:
    - '/System/Library/LaunchAgents/com.apple.notificationcenterui.plist'
    - '/System/Library/LaunchAgents/com.openssh.ssh-agent.plist'

- name: 'Disable the sound effects on boot'
  command: 'nvram SystemAudioVolume=" "'
  become: yes

- name: 'Remove duplicates in the "Open With" menu (also see `lscleanup` alias)'
  command: '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'

- name: 'Remove all items from osx dock'
  shell: 'dockutil --remove all'
