---
dirs:
  - '~/.gnupg'
  - '~/.vim'
  - '~/bin'
  - '~/data/aws/s3/chop-dbhi-brownea'
  - '~/data/gcp/storage/syncopation'

dotfiles:
  - { path: '~/.ansible.cfg', src: '{{ role_path }}/files/ansible.cfg' }
  - { path: '~/.editrc', src: '{{ role_path }}/files/editrc' }
  - { path: '~/.gitconfig', src: '{{ role_path }}/files/gitconfig' }
  - { path: '~/.gitignore', src: '{{ role_path }}/files/gitignore' }
  - { path: '~/.gnupg/gpg.conf', src: '{{ role_path }}/files/gnupg/gpg.conf' }
  - { path: '~/.gnupg/gpg-agent.conf', src: '{{ role_path }}/files/gnupg/gpg-agent.conf' }
  - { path: '~/.gnupg/sshcontrol', src: '{{ role_path }}/files/gnupg/sshcontrol' }
  - { path: '~/.inputrc', src: '{{ role_path }}/files/inputrc' }
  - { path: '~/.iterm2', src: '{{ role_path }}/files/iterm2' }
  - { path: '~/.npmrc', src: '{{ role_path }}/files/npmrc' }
  - { path: '~/.spacemacs', src: '{{ role_path }}/files/spacemacs' }
  - { path: '~/.tmux.conf', src: '{{ role_path }}/files/tmux.conf' }
  - { path: '~/.vim/after', src: '{{ role_path }}/files/vim/after' }
  - { path: '~/.vim/ftplugin', src: '{{ role_path }}/files/vim/ftplugin' }
  - { path: '~/.vim/settings.vim', src: '{{ role_path }}/files/vim/settings.vim' }
  - { path: '~/.vim/vundles', src: '{{ role_path }}/files/vim/vundles' }
  - { path: '~/.vim/vundles.vim', src: '{{ role_path }}/files/vim/vundles.vim' }
  - { path: '~/.vimrc', src: '{{ role_path }}/files/vimrc' }
  - { path: '~/.vimrc.after', src: '{{ role_path }}/files/vimrc.after' }
  - { path: '~/.vimrc.before', src: '{{ role_path }}/files/vimrc.before' }
  - { path: '~/.zsh', src: '{{ role_path }}/files/zsh' }
  - { path: '~/.zsh.after', src: '{{ role_path }}/files/zsh.after' }
  - { path: '~/.zsh.before', src: '{{ role_path }}/files/zsh.before' }
  - { path: '~/.zsh.prompts', src: '{{ role_path }}/files/zsh.prompts' }
  - { path: '~/.zpreztorc', src: '{{ role_path }}/files/zpreztorc' }

git_repos:
  - { dest: '~/.emacs.d', repo: 'git@github.com:syl20bnr/spacemacs.git', version: 'develop' }
  - { dest: '~/.vim/bundle/vundle', repo: 'git@github.com:gmarik/vundle.git' }
  - { dest: '~/.zprezto', repo: 'git@github.com:sorin-ionescu/prezto.git', force: 'yes' }
  - { dest: '~/.fonts', repo: 'git@github.com:powerline/fonts.git' }

git_dotfiles:
  - { path: '~/.zlogin', src: '~/.zprezto/runcoms/zlogin' }
  - { path: '~/.zlogout', src: '~/.zprezto/runcoms/zlogout' }
  - { path: '~/.zprofile', src: '~/.zprezto/runcoms/zprofile' }
  - { path: '~/.zshenv', src: '~/.zprezto/runcoms/zshenv' }
  - { path: '~/.zshrc', src: '~/.zprezto/runcoms/zshrc' }

go_pkgs:
  - 'github.com/nsf/gocode'
  - 'github.com/rogpeppe/godef'
  - 'golang.org/x/tools/cmd/guru'
  - 'golang.org/x/tools/cmd/gorename'
  - 'golang.org/x/tools/cmd/goimports'
  - 'github.com/nats-io/gnatsd'

pip_pkgs:
  - { name: 'git+ssh://git@github.research.chop.edu/devops/aws-auth-cli.git', ignore_errors: 'yes' }

aws_s3_syncs:
  - { src: 's3://chop-dbhi-brownea', dest: '~/data/aws/s3/chop-dbhi-brownea', profile: 'saml', ignore_errors: 'yes' }

gcp_storage_syncs:
  - { src: 'gs://syncopation', dest: '~/data/gcp/storage/syncopation' }
